images_upload_handler: 'assets/tinymce/image/plugin.js'
toolbar:
  - styleselect | bold italic | undo redo
  - image | link
plugins:
  - image
  - uploadimage
  - link
  - code
width: 700
height: 800
