images_upload_handler: 'assets/tinymce/image/plugin.js'
toolbar:
  - styleselect | bold italic | undo redo
  - uploadimage | link
plugins:
  - uploadimage
  - link
  - code
width: 700
height: 800
remove_script_host : true
document_base_url : "http://www.papercutodyssey.dk/"
